# Generated by Django 3.0.5 on 2023-05-01 06:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showtime',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
