# Generated by Django 3.0.5 on 2023-05-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20230501_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
