# Generated by Django 3.0.5 on 2023-04-01 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='movie')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
